### ISSUE TITLE
Brief questionnaire prior to project kick-off

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/just-one-tree#1]
This is a brief questionnaire to get a feel for your project and make sure we're on the same page. If you'd prefer to hash these out over the phone, we can definitely arrange for that, but I typically find it's easiest to answer them on your own time.

Please feel free to be as detailed—or as straightforward!—as you feel is necessary for each question. You can post your answers as a response to this issue, and, once that's done, we'll start working on a look & feel for your site!

- What are your goals and objectives for the new website?
- Think about your current website. Are there any problems you've experienced with it?
- What is the personality and tone you’d like to express with your site? 
- Who is your primary audience for the site?
- Please provide a few examples of websites (or other designs) with a look and feel that appeals to you.

**Comment by Justonetree** [comment]
I think I am in the system now.  Do you need me to resend my answers to your questions in this format?

**Comment by sarahmonster** [comment]
Thanks, @justonetree! I've copied your comment from email here so we can refer back to it. I'll create some more discussion issues next week, and we'll get started on your site!

**Comment by Justonetree** [comment]
Hi Sarah,

How's the progress going on our site?  Wanted to 
let you know that thanks to Josh Elkes, a 
volunteer with JOT, we are able to have special 
access to Getty Images!  For the time being, you 
can use my password.  Josh can set up your own if 
that is preferable, so I have copied him here.

Looking forward to seeing how this all comes 
together!  Thanks again, Isabel

Go to - www.gettyimages.com 
<http://www.gettyimages.com/>
The log in using:
Username - isabelwade@gmail.com 
<mailto:isabelwade@gmail.com>
Password - images123

Isabel Wade
Just One Tree, Chief Lemon Ambassador
415-601-6992

**Comment by Justonetree** [comment]
Thanks for the intro Isabel!
Sarah - Nice to meet you.
Could you please send me your email address? The one on copy is a very long
URL.

Best,
Josh


*Josh Elkes*Joshelkes.com  <http://joshelkes.com/>
C: (914) 774-6117

**Comment by sarahmonster** [comment]
Hi Josh and Isabel! I've been wrapped up with a site launch that ended up being much more complex and time-consuming than originally expected, so unfortunately I haven't been able to get started on your project. I'm aiming to get to it next week and will send you an update then.

Josh, we're using Github to collaborate on the project. If you can go to github.com and set up a free personal account, that will allow you to easily jump in on relevant threads as the project progresses. Just go ahead and set up a free account and then send me the email address you've used to sign up—I'll take care of the rest. 

Look forward to working with you both very soon!

**Comment by Justonetree** [comment]
yahoo!

Isabel Wade
Just One Tree, Chief Lemon Ambassador
415-601-6992

**Comment by Justonetree** [comment]
Want to introduce you to another team member who is very savvy about marketing and branding, Nicole Delma (nicole@fondgroup.com.  I will give her the info that you sent to Josh above, but here is her email in this message.

**Comment by sarahmonster** [comment]
Thanks, Isabel! I've added Nicole's contact information to our records. She can contribute directly to issues via Github as well—she'll just need to sign up for a free account. 

Cheers!

**Comment by Justonetree** [comment]
A couple more ideas discussed between Nicole and myself:
1)  Move social icons down on the home page (or else people just go there) (to bottom?)
2)  Put an email sign-up on upper right (home page)
3)  Move Lemon Spotting under Take Action (i.e. off Home Page)
