### ISSUE TITLE
Custom post type setup

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/just-one-tree#11]
First of all, we'll want to create a custom post type setup for tree registrations. 

Here's how I'd see that breaking down:
- name
- email
- newsletter signup opt-in (yes/no)
- type (individual/organization)
- number of trees
- address 
- neighbourhood (include option for "not sure")
- mobile number (to opt-in to mobile updates)
- other types of fruit trees owned
- description/comment (is this necessary/do people fill it in?)

I've removed the "Do you have a lemon tree? yes/no" question from the data here because the answer would obviously be yes—otherwise nobody would be registering a lemon tree! I've also added the option to self-select a "neighbourhood" from a drop-down list based on the boundaries defined here: https://data.sfgov.org/Geographic-Locations-and-Boundaries/Planning-Neighborhood-Groups-Map/iacs-ws63/data

**Comment by Justonetree** [comment]
Looks good; suggest we eliminate other fruit trees; also, we need mobile related to volunteer ops and urgent info related to citrus disease
