### ISSUE TITLE
Prevent duplicate tree registrations

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/just-one-tree#14]
> Can the registration form check if a given tree has already been registered and notify the user as they’re filling out the form?

We may be able to check for this, but it would likely require some custom work. There are plugins for Gravity Forms that prevent a user from double-clicking and submitting twice (https://en-gb.wordpress.org/plugins/gravity-forms-duplicate-prevention/) but that doesn't sound like what we need here.

What we'd need to do would be to compare fields as entered (email and/or address, probably), compare them against existing database records, and then check for this before submitting the form, asking the submitter to confirm submission if there's a match. 

With email addresses, matching would be pretty straightforward, but addresses would potentially require fuzzy matching, depending on how people enter that data. 

Gravity Forms does have some functionality for this built-in already (the "no duplicates" option for a field) and that functionality can be extended: http://gravitywiz.com/better-limit-submission-per-time-period-by-user-or-ip/ but I'm not sure if that would provide the optimal user experience.

We'll need to investigate this as part of v2.

**Comment by Justonetree** [comment]
Yes, this is important if we can do it

**Comment by sarahmonster** [comment]
I'm going to put this one on hold since it's reasonably complex to implement. I think it's best to launch our v2 first, and then see if we actually need this functionality.

**Comment by sarahmonster** [comment]
Closing this issue since I don't think it's strictly required. We can reopen if we establish a real need for this functionality.
