### ISSUE TITLE
Button text is slightly off center

### ISSUE THREAD

**Issue by michiecat** [a8cteam51/just-one-tree#30]
I feel like the text on top of buttons could use more vertical centering (I noticed this in Chrome, Firefox, and Safari): 

![screen shot 2017-01-13 at 11 28 17 am](https://cloud.githubusercontent.com/assets/1385492/21953126/e6444224-d9e3-11e6-86d4-b44cb6353549.png)

**Comment by sarahmonster** [comment]
Looks like the text is green too, where it should definitely be not-green. Might be an inheritance issue with :visited.
