### ISSUE TITLE
Align join campaign button to left?

### ISSUE THREAD

**Issue by michiecat** [a8cteam51/just-one-tree#33]
Somehow the alignment of the join campaign button in the footer feels a little off to me...I'm not sure if it's because it is centered and might look better aligned to the left or full-width? This could just be me, so feel free to ignore.

**Comment by sarahmonster** [comment]
Nope, I think I'd agree. It fit a bit better at an earlier iteration, but since I juggled the elements in the footer, it feels rather awkward. Good call!
