### ISSUE TITLE
Search result title - could have more variation from post titles

### ISSUE THREAD

**Issue by michiecat** [a8cteam51/just-one-tree#34]
The search result title looks very similar to the post titles...perhaps it could have a more distinct look so that it's set off a bit?

<img width="738" alt="screen shot 2017-01-13 at 11 38 39 pm" src="https://cloud.githubusercontent.com/assets/1385492/21953366/b0549ac8-d9e9-11e6-97bc-5b687eb2b52b.png">

**Comment by sarahmonster** [comment]
I thought that was a poorly-chosen line-height on first look. Definitely needs a fix—script typeface may be the best choice. Honestly I'm not sure I've even looked at the search results page, so it probably need some love. 😱
