### ISSUE TITLE
Archive listings - more visual separation?

### ISSUE THREAD

**Issue by michiecat** [a8cteam51/just-one-tree#37]
#This is somewhat related to #34. I feel like there could be some more visual separation between posts in the listings. Maybe a subtle top or bottom border (like on the front page), and more margins? 

<img width="957" alt="screen shot 2017-01-14 at 12 07 09 am" src="https://cloud.githubusercontent.com/assets/1385492/21953487/c15671bc-d9ed-11e6-8123-2f07c1fbcaea.png">

**Comment by sarahmonster** [comment]
Related: #29. I've ignored post stylings a bit for this theme. ;)
