### ISSUE TITLE
Create a style guide for new site

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/just-one-tree#4]
The first thing I'm going to work on is creating a style guide for the new site. This will give us a sense of colours, typography, imagery, and patterns to use for the site. I'll get an initial guide done this week to show you—we can then revise back & forth until we land on a style you like.

Once we have that ready, we'll jump right into building the site!

**Adjectives:** Sincere, friendly, community-based

**Audience:** ...primarily millennials interested in urban ag and the environment and home owners (boomers) thinking about their garden and also concerned about the environment

**Other sites:** [Walk San Francisco](http://walksf.org/), [Education Outside](https://www.educationoutside.org/), [San Francisco Beautiful](http://sfbeautiful.org/), [Friends of the Urban Forest](http://www.fuf.net/)

**Comment by Justonetree** [comment]
Sounds good;  looking forward to it!

Isabel Wade
Just One Tree, Chief Lemon Ambassador
415-601-6992

**Comment by sarahmonster** [comment]
I've been working on a style guide to show you this week, and here's what I've got so far:

http://concierge.mystagingwebsite.com/justonetree/assets/style-guide/

What you're looking at here obviously isn't a full website—it's just a stylistic guideline, to get a sense of the overall look & feel of the site. What we've established here is the basics: colours, typography, buttons, and some graphic elements. The aim here is to get a sense of how the site will look & feel, make sure we're on the same page, and then we can move forward with building the site itself. Things will likely change and adapt as we work on the actual design of the site.

I've tried to keep things bright, friendly, and clean, while adding a bit of texture for visual interest. We could definitely push it a bit more to either side: either cleaner, or more textured, depending on your vision for the site. There are lots of beautiful illustrations heavily featuring lemons (I spent a while browsing Getty) that I think could be incorporated to great effect—it's just about choosing the right tone!

Let me know your thoughts, and we'll go from there.

**Comment by Justonetree** [comment]
Wow!  I love what you have done.  Meets all the criteria I mentioned- with your lovely add-ons!

**Comment by Justonetree** [comment]
Hi Sarah,

Hi.  I'm wondering if you are making any 
progress?  We are hoping to launch a fall campaign 
to plant and register lemons but don't want to do 
it until we have the new website up.  Do you have 
enough time to finish?  Is there anything we can 
do on our end? Thanks very much!  Isabel

Isabel Wade
Just One Tree, Chief Lemon Ambassador
415-601-6992

**Comment by sarahmonster** [comment]
Hi Isobel, 

Things have been progressing a bit more slowly than usual on my end, mostly due to other projects & time commitments. But it's shaping up nicely! I should have a more concrete update for you by early next week, and hopefully a demo site to show as well.

At that stage, I'll also re-evaluate the project and we'll put together an estimated timeline for the project. There are a few more complex elements of the site that I'll need to discuss with co-workers, but I'd expect we could be ready to launch late October or early November. 

Cheers!

**Comment by Justonetree** [comment]
Wonderful!  Thanks so much for letting me know;  
can't wait to see the demo!  Best, isabel

Isabel Wade
Just One Tree, Chief Lemon Ambassador
415-601-6992
