### ISSUE TITLE
Submenu suggestions

### ISSUE THREAD

**Issue by michiecat** [a8cteam51/just-one-tree#48]
Some ideas for the submenus:

* How about a subtle shadow on the submenus to help them stand out from the background?
* The black top border of the submenus feels a little harsh...maybe a shade of brown would be softer here. 
* Alternatively what if you remove the top border and tried a small upward-pointing arrowhead/triangle or a heart shape (similar to the hearts in the logo and on the treeometer) at the top of the submenu that's the same color as the rest of the submenu?

**Comment by sarahmonster** [comment]
Great suggestions, thank you! It looks about a million times better now. ❤️
