### ISSUE TITLE
Fine-tune illustrations on front page

### ISSUE THREAD

**Issue by michiecat** [a8cteam51/just-one-tree#49]
Overall I think the illustrations are ❤️ and don't need any tweaks for v1. But you were looking for suggestions and so the below are all nit-picks (and could really be added in a v2 if you wanted to):

1. Glass of lemonade -- The straw stripes could be green.  Alternatively, the little cores inside the lemon (not sure of the correct term) that are currently light yellow could be alternating with a light green? 

2. Glass of lemonade -- As an alternative to the green/yellow suggested above, I wonder how the lemon "cores" would look with the colors from the Just One Tree logo, in the light/muted shades. This would break away from the established green/yellow pattern with all the other logos but I think it'd be fun and would add visual interest, plus reflect the JOT branding in a subtle way. Establish a pattern, break away once, then back to the yellow/green with the final illustration. 

I think the colors in the get involved logo are fine, personally.

**Comment by sarahmonster** [comment]
Thanks for the feedback! I think it's best to have a think about these & revisit them with a fresh brain post-launch.

**Comment by sarahmonster** [comment]
I'm going to close this issue—at this stage, if I were to adjust to illustrations, I'd want to redraw them a bit for clearer line shapes & better consistency, but I don't think there's a huge benefit to JOT in my spending the time to do that right now, so it'd be better to invest that energy elsewhere.
