### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/just-one-tree#5]
@Justonetree Let's discuss the homepage of the site, since this is an important element of the site. You mentioned it a few times in #1:

> to be able to update the site easily, especially the home page, by myself ... I've not been able to and I really want to keep it fresh.
> 
> 2) to motivate action (i.e. either register the lemon tree you have or go out and purchase one to
> plant- and then register it) 
> 
> I don't like heavy push for donations on the home page; I'm not sure about flashing photos- think they are distracting and a bit jarring

The homepage is definitely an important part of the site, so I think it could do with some special attention to ensure that it's doing it job as best as it can. Right now, there are a lot of different things on the homepage, and I think it might be a bit hard to separate out the most important bits. 

What actions and information are most important to highlight here?

**Comment by sarahmonster** [comment]
From #1:

>
A couple more ideas discussed between Nicole and myself:
1) Move social icons down on the home page (or else people just go there) (to bottom?)
2) Put an email sign-up on upper right (home page)
3) Move Lemon Spotting under Take Action (i.e. off Home Page)

@Justonetree perhaps you can give me a list of the most important elements to be included on the home page, and I'll work from there?

**Comment by Justonetree** [comment]
Hi Sarah,

Home Page Thoughts

1)  Visually appealing with photos; simple

2)  Mission/goal very clear and prominent and 
large font;  some indication that the project is 
in SAN FRANCISCO

3)  Tree Counter ( some visual with total # of 
lemon trees to date)

4)  Take Action:  How to Participate & Make a 
Difference (photo of someone planting a lemon tree)

(below could be tabs or buttons only)

     a) *Register* the lemon tree you've got or 
register other lemon trees you          spot 
around the City

     b) *Plant* a lemon tree:  your sunny window, 
back yard, in public                      orchards

     c) *Share* extra lemons

     d) *Donate: *time or funds to expand public 
orchards

5)  Top right (and every page):  Join our Email List

6)  Bottom:  Put Social Media and Donate Buttons

Nicole suggested the following websites 
emphasizing good visuals, simplicity and mission 
clarity.  I especially love Nature.Org

http://www.nature.org
http://www.ru4children.org/#home
http://themandalacenter.com/about
http://undertheweather.eu
https://www.notforsalecampaign.org
http://www.surfrider.org

      Can you please include Nicole in our 
discussion?  Many thanks! Isabel

Isabel Wade
Just One Tree, Chief Lemon Ambassador
415-601-6992
