### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/just-one-tree#6]
> we have no newsletter to send anyone but do want to have a complete file of registered lemon owners so we can send them occasional care info and progress report perhaps once a year

The homepage currently has a "sign up" link that goes to a Mailchimp newsletter: http://justonetree.us5.list-manage1.com/subscribe?u=5d4723abc8e0474f83dbea01f&id=cb4c34866f

@Justonetree are you using this Mailchimp newsletter at all?

**Comment by Justonetree** [comment]
I am searching for tree list and there seem to be 
several, but none that are current! Will send what 
I've got (link) in a bit. Meanwhile, see below for 
answers to questions on newsletter & Mail Chimp:

Isabel Wade
Just One Tree, Chief Lemon Ambassador
415-601-6992

On 8/8/16 1:41 PM, sarah ✈ semark wrote:
>
>     we have no newsletter to send anyone but do
>     want to have a complete file of registered
>     lemon owners so we can send them occasional
>     care info and progress report perhaps once a
>     year
>
> The homepage currently has a "sign up" link that 
> goes to a Mailchimp newsletter: 
> http://justonetree.us5.list-manage1.com/subscribe?u=5d4723abc8e0474f83dbea01f&id=cb4c34866f
>
Would this be a separate list from the list of 
registered owners that I have created? Can you see 
the data?  Are any dates available and are they 
current?

Would like an email sign-up upper right on home 
page, but not promising a newsletter (perhaps 
Campaign updates? or nothing?)

**Comment by sarahmonster** [comment]
Fixed via #15.
