### ISSUE TITLE
Main nav breaks just below viewport width of 777px

### ISSUE THREAD

**Issue by danielwrobert** [a8cteam51/just-one-tree#60]
The Main nav runs out of room for some of the elements below 777px. The easiest fix is probable setting the mobile nav to kick in at a 776px media-query.

See screenshot:

<img width="774" alt="screenshot 2017-01-24 11 36 04" src="https://cloud.githubusercontent.com/assets/481776/22256911/2bc26c56-e22a-11e6-9346-c34168c934f6.png">

**Comment by sarahmonster** [comment]
There's actually a `<span class="hide">` used on some of the menu items on the original site to avoid this issue—I've re-added those now.
