### ISSUE TITLE
Ability to add photos and additional text on the front page

### ISSUE THREAD

**Issue by michiecat** [a8cteam51/just-one-tree#65]
The client expressed wanting the ability to add photos and text to the front page to highlight events and projects. They want to keep the video, "What's New" and Treemometer the same, but they'd like to be able to drop in photos from time to time to keep the front page content fresh. 

I did tell them that having too much content on the front page would make things look too busy, and the "What's New" section will be updated whenever they make a new post. 

The idea that came up during the meeting was to add an additional row of three images (3 columns), with text below the photos. 

However, I think adding featured images to What's New?" could be a cleaner way to handle this without adding more things to the front page. The point of that section is to highlight the latest, so with featured images, that might be all they need.

**Comment by sarahmonster** [comment]
> However, I think adding featured images to What's New?" could be a cleaner way to handle this without adding more things to the front page. The point of that section is to highlight the latest, so with featured images, that might be all they need.

This would probably be a much more elegant solution here. I'm a bit wary of adding images for the sake of adding images, rather than as a content-driven decision. 

Will add this to my list to discuss via email so we can sort out the best approach for their content requirements.

**Comment by wrightcj03** [comment]
I recommended moving this to a later phase. I'll work with the client to gather requirements and examples in the meantime!

**Comment by sarahmonster** [comment]
Closing this for now since it doesn't seem to be high-priority or high-impact. Will re-open if it's requested again!
