### ISSUE TITLE
Thumbnail grid gallery caption styling

### ISSUE THREAD

**Issue by michiecat** [a8cteam51/just-one-tree#66]
Linda liked the tiled galleries that we set up, but she prefers to always show captions instead of only on hover. She’s fine with having them show up on hover for now, but for v2 maybe we can look into optimizing the caption (and overall) styles for galleries set to display with the “Thumbnail Grid” option. since that’s the only gallery view that always shows captions.

**Comment by sarahmonster** [comment]
Example tiled gallery page: http://justonetree.org/current-projects-2/jjc/ 

Can you send me an example of a thumbnail grid gallery page that has captions? I can't seem to find one but I may be looking in the wrong spot.

**Comment by sarahmonster** [comment]
Ping @michiecat ^

**Comment by michiecat** [comment]
I couldn't find any examples either; they've all seemed to be converted to the mosaic style. I put a test thumbnail grid example together here: https://justonetree.mystagingwebsite.com/?p=3241&preview=true
