### ISSUE TITLE
Enter all neighbourhoods

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/just-one-tree#69]
We're going to be using the neighbourhoods listed here:
https://data.sfgov.org/Geographic-Locations-and-Boundaries/Planning-Neighborhood-Groups-Map/iacs-ws63/data

Each one will need to be entered as an individual taxonomy.

**Comment by wrightcj03** [comment]
I downloaded a [CSV version](https://docs.google.com/spreadsheets/d/1hnTMeiv9wbxF5GfGDw12mlT3M14njeCppPUpGBcZXbo/edit#gid=1634504588) of the map you linked to and added them to the neighborhoods taxonomy. 

One thing to note—there were a few neighborhoods in the taxonomy already. There are 33 neighborhoods in the CSV and 34 in the taxonomy. I don't see any duplicates but I wanted to point this out in case something weird presented itself later!

**Comment by sarahmonster** [comment]
That's perfect; thank you! I'd already added a few for testing, so that's why they were there. :)
