### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/just-one-tree#7]
> we don't have events to invite the public to, but want to report on the planting events/projects we are working on. We could add instead an opportunity for people to request a speaker for their Garden Club or neighborhood organization.

@Justonetree I'm a bit unclear on what you're looking for here. Can you clarify a bit for me?

**Comment by Justonetree** [comment]
I can't quite remember what your original question 
was linked to (a box on the home page?) but my 
reply relates to websites that feature "current" 
activities for people to participate in.  We get 
inquiries about people participating in tree 
planting, but we only do about 2 a year- mostly 
people are being motivated to plant in their own 
spaces.  So I thought this 'box' could be an 
opportunity for people to request a JOT speaker 
for their neighborhood or civic group.  Or, we 
could highlight that our biggest volunteer need is 
for "Lemon Spotters." (explained on lemon spotter 
page)

Isabel Wade
Just One Tree, Chief Lemon Ambassador
415-601-6992
