### ISSUE TITLE
Assign existing registrations to neighbourhoods

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/just-one-tree#72]
Once we have the existing tree registrations imported (#67), we'll need to see if we can assign those registrations to neighbourhood taxonomies.

The existing tree registrations don’t have the neighbourhood taxonomies—just address and zipcode. If I can geolocate them by address (ie, get the coordinates—I should be able to do this) would there be a way to determine what neighbourhood the records fall into programmatically?

Ideally this would be via a script that we could run once and have it adjust all the custom post types. There are 1117 records of tree registrations, so that would be pretty painful to handle manually. I'm thinking maybe a wp-cli script, but that would depend on whether we could access a geolocator via wp-cli.

Once we get coordinates, I'm hoping that we'd be able to place those coordinates within one of the map boundaries (#3), but I'm not exactly sure how/if that would work.

**Comment by michiecat** [comment]
We had chatted earlier about this possibly being accomplished via find/replace to add the neighborhoods to the spreadsheet prior to importing. Does that still look doable?

**Comment by sarahmonster** [comment]
Doing this is going to be a bit of a dance, but I think I've sorted out a sensible solution. First, I spent a few hours manually mapping zip codes to neighbourhoods. 

I ended up with this:
https://docs.google.com/spreadsheets/d/195Z7wwXT96xBmPdq-dDrNs0lkhfSPlQo_E5ixg772PM/edit?usp=sharing

I used a few different data sources, since there's no real canonical source here:
https://data.sfgov.org/Geographic-Locations-and-Boundaries/Bay-Area-ZIP-Codes/u5j3-svi6
https://www.maptechnica.com/search
https://data.sfgov.org/Geographic-Locations-and-Boundaries/San-Francisco-ZIP-Codes/srq6-hmpi
https://data.sfgov.org/Geographic-Locations-and-Boundaries/Planning-Neighborhood-Groups-Map/iacs-ws63/data
http://sanfranguide.com/zip-codes/

There was some conflict between sources but I did my best to common-sense it.

Every zip code with more than one entry has a neighbourhood association; other entries will just be added to an "uncategorized" or "Greater Bay Area" neighbourhood. These can then be either manually dealt with by Isabel or left out of the map, depending on how we handle #3.

Rather than doing a find-and-replace, since we'll need to do a number of imports, I'd like to build a super-simple function to map zip codes to neighbourhoods, and convert the zip code to a neighbourhood on import. (See http://www.wpallimport.com/tour/execute-php-on-data/) I'll work on getting this put together while we double-check the neighbourhood mappings with Isabel.

**Comment by sarahmonster** [comment]
This was done a while ago with #74. All records are up on the staging site.
