### ISSUE TITLE
"Fun" interactive element

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/just-one-tree#8]
> Would be great if we could add a fun element (ie. a lemon Pokemon!) perhaps to inspire tree
> registration (all we need is the address-you don't have to own the tree to register it) but we
> would need a way to sort duplicates (something needs to pop up,as on the Friends of the Urban
> Forest Map, that indicates there is a tree already registered if I try to put in a tree).
> 
> We have a new partnership with Lemonade Restaurants so perhaps we could get them to offer
> a free lemonade for every 5 trees someone registers (but then we need the back end to spit
> out a list of lemon spotters and how many they have registered).

**Comment by Justonetree** [comment]
Hi Sarah,

How are you doing?  I am still trying to find the 
tree registry files;  I don't know if anything I 
sent you helped in this. Should I be looking at 
Git Hub?  Not quite sure of our process here and 
what I should/could be doing.  Best, Isabel

Isabel Wade
Just One Tree, Chief Lemon Ambassador
415-601-6992

**Comment by sarahmonster** [comment]
This is unclear and doesn't really mean or add anything, so I'm closing in the interests of keeping v2 as simple as possible.
